version: '3.9'

services:
  # server:
  #   build: ./server
  #   container_name: classbuddy_server
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./server:/app
  #     - /app/__pycache__
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #     - WATCHFILES_FORCE_POLLING=true
  #   command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
  #   restart: unless-stopped

  client:
    build: ./client
    container_name: classbuddy_client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules 
    command: npm run dev
