version: '1.0'

services:
  server:
    build: ./server
    container_name: classbuddy_server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  client:
    build: ./client
    container_name: classbuddy_client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules 
    depends_on:
      - server
    command: npm run dev